  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - quarkus-graalvm-aws-lambda-arm64-1.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    QuarkusLambda:
      Type: AWS::Serverless::Function
      Properties:
        Architectures:
          - arm64
        Handler: not.used.in.provided.runtime
        Runtime: provided.al2
        CodeUri: function.zip
        MemorySize: 256
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
        Events:
          Api:
            Type: Api
            Properties:
              Path: /{proxy+}
              Method: any
              RestApiId: !Ref ApiDeployment
    ApiDeployment:
      Type: AWS::Serverless::Api
      Properties:
        StageName: !Ref Stage

  Parameters:
    Stage:
      Type: String
      Default: 'prod'

  Outputs:
    QuarkusLambdaApi:
      Description: URL for application
      Value: !Sub 'https://${ApiDeployment}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
      Export:
        Name: QuarkusLambdaApi
